---
config:
  theme: neo
---
flowchart TD
        A(["Definir saldo "])
        A --> B{"¿Cuánto desea retirar?"}
        B --> C["retiro"]
        C --> D["Retire su dinero"]
        C --> E["No tienes fondos"]
        D --> F["Fin"]
